name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create HTML File
      run: echo '<!DOCTYPE html><html lang="en"><head><title>ESA 6</title></head><body><h1>Hello, GitHub Actions!</h1></body></html>' > ESA6.html

    - name: Display HTML File
      run: cat ESA6.html
