name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Build
      run: npm run build  # Dieser Schritt sollte den Build durchführen

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages --force
